version: '3'
services:

  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: webapp_dev
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: Postgres@0601
      volumes: /path/on/host:/path/in/container